spring.datasource.url=jdbc:mysql://localhost:3306/db_usuarios
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

#SMTP significa Simple Mail Transfer Protocol (Protocolo Simples de Transfer�ncia de Correio).
#O que � SMTP?
#� o protocolo padr�o utilizado para enviar emails na internet. Pense nele como o "carteiro digital" que transporta suas mensagens de um servidor para outro at� chegar ao destino.

#SSL significa Secure Sockets Layer (Camada de Soquetes Segura).
#O que � SSL?
#� um protocolo de seguran�a que criptografa a comunica��o entre dois sistemas (como seu aplicativo e o servidor do Gmail), garantindo que os dados trafeguem de forma segura e n�o possam ser interceptados ou lidos por terceiros.



#Define o servidor SMTP do Gmail que ser� usado para enviar os emails
spring.mail.host=smtp.gmail.com

#Porta para conex�o SMTP com SSL (465 � a porta padr�o para SMTP com SSL)
spring.mail.port=456

#Seu endere�o de email do Gmail que ser� usado como remetente
spring.mail.username=test3mail5566@gmail.com

#Senha de aplicativo do Gmail (n�o � sua senha normal do Google, mas uma senha espec�fica gerada para aplicativos)
spring.mail.password=

#Habilita autentica��o SMTP - necess�rio para provar que voc� � quem diz ser
spring.mail.properties.mail.smtp.auth=true

#Ativa o uso de SSL na conex�o, criptografando a comunica��o
spring.mail.properties.mail.smtp.ssl.enable=true

#Define que o servidor smtp.gmail.com � confi�vel para conex�es SSL
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com


#Tempo m�ximo (em milissegundos) para estabelecer a conex�o inicial (10 segundos)
spring.mail.properties.mail.smtp.connectiontimeout = 10000

#Timeout de leitura de dados do servidor (10 segundos)
spring.mail.properties.mail.smtp.timeout=10000

#Timeout para escrita de dados para o servidor (10 segundos)
spring.mail.properties.mail.smtp.writetimeout=10000

#Ativa logs detalhados do m�dulo de email do Spring Framework
logging.level.org.springframework.mail=DEBUG

#Ativa logs detalhados da biblioteca Angus Mail (implementa��o JavaMail usada pelo Spring)
logging.level.org.eclipse.angus.mail=DEBUG
