spring.datasource.url=jdbc:mysql://localhost:3306/db_usuarios
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

#SMTP significa Simple Mail Transfer Protocol (Protocolo Simples de Transferência de Correio).
#O que é SMTP?
#É o protocolo padrão utilizado para enviar emails na internet. Pense nele como o "carteiro digital" que transporta suas mensagens de um servidor para outro até chegar ao destino.

#SSL significa Secure Sockets Layer (Camada de Soquetes Segura).
#O que é SSL?
#É um protocolo de segurança que criptografa a comunicação entre dois sistemas (como seu aplicativo e o servidor do Gmail), garantindo que os dados trafeguem de forma segura e não possam ser interceptados ou lidos por terceiros.



#Define o servidor SMTP do Gmail que será usado para enviar os emails
spring.mail.host=smtp.gmail.com

#Porta para conexão SMTP com SSL (465 é a porta padrão para SMTP com SSL)
spring.mail.port=456

#Seu endereço de email do Gmail que será usado como remetente
spring.mail.username=test3mail5566@gmail.com

#Senha de aplicativo do Gmail (não é sua senha normal do Google, mas uma senha específica gerada para aplicativos)
spring.mail.password=

#Habilita autenticação SMTP - necessário para provar que você é quem diz ser
spring.mail.properties.mail.smtp.auth=true

#Ativa o uso de SSL na conexão, criptografando a comunicação
spring.mail.properties.mail.smtp.ssl.enable=true

#Define que o servidor smtp.gmail.com é confiável para conexões SSL
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com


#Tempo máximo (em milissegundos) para estabelecer a conexão inicial (10 segundos)
spring.mail.properties.mail.smtp.connectiontimeout = 10000

#Timeout de leitura de dados do servidor (10 segundos)
spring.mail.properties.mail.smtp.timeout=10000

#Timeout para escrita de dados para o servidor (10 segundos)
spring.mail.properties.mail.smtp.writetimeout=10000

#Ativa logs detalhados do módulo de email do Spring Framework
logging.level.org.springframework.mail=DEBUG

#Ativa logs detalhados da biblioteca Angus Mail (implementação JavaMail usada pelo Spring)
logging.level.org.eclipse.angus.mail=DEBUG
